In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20,2) #2 is the stepsize

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros((5,5)) #(5,5) is tuple and first is the row and second is the column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,4)) #two dimensional have two brackets

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,10) 
#one dimensional, up to 10 evenly spaced points between 0 to 5)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.linspace(0,10,10) 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.linspace(0,10,100) 

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4) #identity matrice

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5) # 5 random numbers

array([0.09321064, 0.47212035, 0.69513542, 0.65413985, 0.8184667 ])

In [16]:
np.random.rand(5,5)

array([[0.52926109, 0.6271869 , 0.33163995, 0.01635847, 0.46500854],
       [0.3876945 , 0.61080514, 0.02446396, 0.78851057, 0.70103896],
       [0.12704989, 0.66706566, 0.52267681, 0.7446115 , 0.76392601],
       [0.69297825, 0.01819142, 0.36370211, 0.19189599, 0.25702815],
       [0.58593753, 0.65628358, 0.64861716, 0.02797687, 0.78070253]])

In [17]:
np.random.randn(2) 

array([-1.63975356, -1.94622134])

In [18]:
np.random.randn(4,4) 

array([[ 1.74987822, -1.5991974 , -0.24455902, -0.14166793],
       [ 1.25235727,  0.90379207,  0.0737464 ,  1.16902557],
       [-1.50473313, -0.8394091 , -1.59604112,  0.03002117],
       [-1.35032234, -0.86133547, -0.70062974, -0.18753817]])

In [19]:
np.random.randint(1,100,10) #10 random integers from 1 to 99

array([21, 82, 71, 56, 75, 45, 47, 60, 80, 83])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
ranarr

array([13, 39, 46, 38, 45, 12,  8, 38, 39, 45])

In [24]:
arr.reshape(5,5) #arr has 25 numbers, this reshape it into row and column.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#to find max and mim number

In [26]:
ranarr

array([13, 39, 46, 38, 45, 12,  8, 38, 39, 45])

In [27]:
ranarr.max()

46

In [28]:
ranarr.min()

8

In [29]:
ranarr

array([13, 39, 46, 38, 45, 12,  8, 38, 39, 45])

In [30]:
ranarr.argmax() 
#To find the max number. 
#The highest number is located at the second location.

2

In [31]:
ranarr.argmin()

6

In [32]:
arr.shape 
#to check the dimension of the array. arr now is a one dimensional array.

(25,)

In [33]:
arr = arr.reshape(5,5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype #to check the data-type of the array

dtype('int32')

In [37]:
## Lecture 19

In [38]:
import numpy as np

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8] #indexing start from zero

8

In [42]:
arr[1]

1

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:3]

array([0, 1, 2])

In [45]:
arr[:6] #start from 0 and up to 6

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[2:] #from index 2 (0,1,2) up to the last

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:6]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [55]:
slice_of_arr[:]=99

In [56]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [57]:
arr #It will replace the original! Be careful

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr_copy = arr.copy() #to copy the array

In [59]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr #Uneffected

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
### Matrics

In [64]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[0][0]

5

In [67]:
arr_2d[0]

array([ 5, 10, 15])

In [68]:
arr_2d[1][1]

25

In [69]:
arr_2d[2][1] #row first then column second

40

In [70]:
arr_2d[1,2] #same as double bracket

30

In [71]:
arr_2d[:2,1:] 
#grab everything no include 2 (35,40,45)
#grab 1 to the last (not including 5,20,35)

array([[10, 15],
       [25, 30]])

In [72]:
arr_2d[:3,2:]

array([[15],
       [30],
       [45]])

In [73]:
#Conditional selection

In [74]:
arr = np.arange(1,11)

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 5 #Give us boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
bool_arr = arr > 5

In [78]:
bool_arr # we can use this boolean array to set condition

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr[arr>5] #remember this 

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr<4]

array([1, 2, 3])

In [82]:
arr_2d = np.arange(50).reshape(5,10)

In [83]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
#to get 31 to 36 and 41 to 46

In [85]:
arr_2d[3:,1:7]

array([[31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46]])

In [86]:
##NumPy Operations

In [87]:
arr = np.arange(0,11)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr + arr*2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr**arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [97]:
1 / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [98]:
np.sqrt(arr) #np is the guy

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [99]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [100]:
np.max(arr)

10

In [101]:
np.min(arr)

0

In [102]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])